version: "3.8"

services:
  sanguchoapp:
    image: martinsangucho/sanguchoimg:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sanguchoapp.entrypoints=http"
        - "traefik.http.routers.sanguchoapp.rule=Host(`sanguchoapp.byronrm.com`)"
        - "traefik.http.middlewares.sanguchoapp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.sanguchoapp.middlewares=sanguchoapp-https-redirect"
        - "traefik.http.routers.sanguchoapp-secure.entrypoints=https"
        - "traefik.http.routers.sanguchoapp-secure.rule=Host(`sanguchoapp.byronrm.com`)"
        - "traefik.http.routers.sanguchoapp-secure.tls=true"
        - "traefik.http.routers.sanguchoapp-secure.tls.certresolver=http"
        - "traefik.http.routers.sanguchoapp-secure.service=sanguchoapp"
        - "traefik.http.services.sanguchoapp.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
