version: "3.8"

services:
  ulloaapp:
    image: ulloaimg:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ulloaapp.entrypoints=http"
        - "traefik.http.routers.ulloaapp.rule=Host(ulloaapp.byronrm.com)"
        - "traefik.http.middlewares.ulloaapp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.ulloaapp.middlewares=ulloaapp-https-redirect"
        - "traefik.http.routers.ulloaapp-secure.entrypoints=https"
        - "traefik.http.routers.ulloaapp-secure.rule=Host(ulloaapp.byronrm.com)"
        - "traefik.http.routers.ulloaapp-secure.tls=true"
        - "traefik.http.routers.ulloaapp-secure.tls.certresolver=http"
        - "traefik.http.routers.ulloaapp-secure.service=ulloaapp"
        - "traefik.http.services.ulloaapp.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
