version: "3.8"

services:
  tonyapp:
    image: tonyimg:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tonyapp.entrypoints=http"
        - "traefik.http.routers.tonyapp.rule=Host(tonyapp.byronrm.com)"
        - "traefik.http.middlewares.tonyapp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.tonyapp.middlewares=tonyapp-https-redirect"
        - "traefik.http.routers.tonyapp-secure.entrypoints=https"
        - "traefik.http.routers.tonyapp-secure.rule=Host(tonyapp.byronrm.com)"
        - "traefik.http.routers.tonyapp-secure.tls=true"
        - "traefik.http.routers.tonyapp-secure.tls.certresolver=http"
        - "traefik.http.routers.tonyapp-secure.service=tonyapp"
        - "traefik.http.services.tonyapp.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true