version: "3.8"

services:
  proyecto_quintoa:
    image: proyecto_quintoa_img:latest
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.entrypoints=http"
        - "traefik.http.routers.proyecto_quintoa.rule=Host(`proyecto_quintoa.byojo.com`)"
        - "traefik.http.middlewares.proyecto_quintoa-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.proyecto_quintoa.middlewares=proyecto_quintoa-https-redirect"
        - "traefik.http.routers.proyecto_quintoa-secure.entrypoints=https"
        - "traefik.http.routers.proyecto_quintoa-secure.rule=Host(`proyecto_quintoa.byojo.com`)"
        - "traefik.http.routers.proyecto_quintoa-secure.tls=true"
        - "traefik.http.routers.proyecto_quintoa-secure.tls.certresolver=http"
        - "traefik.http.routers.proyecto_quintoa-secure.service=proyecto_quintoa"
        - "traefik.http.services.proyecto_quintoa.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true